### ISSUE TITLE
Image format specification for torch.utils.data.Dataset

### ISSUE THREAD

**Issue by dougsouza** [toshas/torch-fidelity#22]
I read everywhere trying to figure out how my datasets should output an image (i.e. which transforms to use). There is nowhere in the docs. As far I found in the code, it seems to be a torch uint8 tensor of the shape (C, H, W):

```python
register_dataset(
    'cifar10-train',
    lambda root, download: Cifar10_RGB(root, train=True, transform=TransformPILtoRGBTensor(), download=download)
)

class TransformPILtoRGBTensor:
    def __call__(self, img):
        vassert(type(img) is Image.Image, 'Input is not a PIL.Image')
        width, height = img.size
        img = torch.ByteTensor(torch.ByteStorage.from_buffer(img.tobytes())).view(height, width, 3)
        img = img.permute(2, 0, 1)
        return img
```

Is that it? The metrics expects torch uint8 tensors? What about sizes? What size of images the dataset should output? The same size as the generator?

Thanks

**Comment by toshas** [comment]
The data type (and shape) should be compatible with the feature extractor in use. Since you are using the default InceptionV3, it expects dtype=uint8. As for size, this particular feature extractor resizes all inputs to a canonical size (299x299 IIRC) internally, so it is size-invariant in some sense.
