### ISSUE TITLE
Some question about 'calculate_metrics'

### ISSUE THREAD

**Issue by chenquan-hdu** [toshas/torch-fidelity#27]
Hi,

I have some problems when using 'calculate_metrics' to calculate FID and KID, and I hope to get your help.
Q: I only have 200 groups of images (each containing gt.png and out.png), how do I call calculate_metrics? 
How to change the input in `calculate_metrics(input1, input2,kid=True)`?

Thank you.

**Comment by toshas** [comment]
Hi, the questions is whether you need FID/KID at all when your data is clearly paired. FID/KID compare distributions, that is they can give you a "distance" between two unordered sets of samples. You could of course compose the two said sets from all gt and all out, but the resulting value would be hard to interpret. I would suggest to take a look into perceptual similarity metrics, such as LPIPS (which is also implemented in torch_fidelity, just can only be accessed programmatically). Feel free to ask followup questions in this ticket despite it being closed.

**Comment by lizijue** [comment]
> Hi, the questions is whether you need FID/KID at all when your data is clearly paired. FID/KID compare distributions, that is they can give you a "distance" between two unordered sets of samples. You could of course compose the two said sets from all gt and all out, but the resulting value would be hard to interpret. I would suggest to take a look into perceptual similarity metrics, such as LPIPS (which is also implemented in torch_fidelity, just can only be accessed programmatically). Feel free to ask followup questions in this ticket despite it being closed.

Hi, 

I also calculate the FID , KID and LPIPS scores between pair images (predictions and GTs), and I am comparing two networks, but the results show the model that has a lower LPIPS value but higher FID and KID scores at the same time. 

So I wanna know is this what you say hard to interpret? What may be the reason for this phenomenon? Could it be a lack of diversity since the higher similarity?

I will very appreciate if you could help me.
